import Head from "next/head";
import Image from "next/image";
import cn from "classnames";

import classes from "./index.module.css";

export default function Home() {
  return (
    <div className={classes.container}>
      <Head>
        <title>Dark Side — жидкости для электронных испарителей</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={classes.descriptionHeader}>
        жидкости для электронных испарителей
      </header>
      <header className={classes.logoHeader}>dark side of the moon</header>
      <section className={classes.itemsContainer}>
        <section className={classes.itemContainer}>
          <div className={classes.itemContainerWrapper}>
            <div className={classes.itemImageWrapper}>
              <Image
                className={classes.itemImage}
                src="/images/items/asteroid/item-asteroid_h7wtml_c_scale,w_200.png"
                layout="fill"
                objectFit="contain"
                alt="Asteroid"
              />
            </div>
            <div className={classes.itemHeaderWrapper}>
              <header className={cn(classes.itemHeader, classes.asteroid)}>
                asteroid
              </header>
            </div>
            <div className={classes.itemCapacity}>60 / 100 ml</div>
            <div className={classes.itemDescription}>
              Густой насыщенный вкус сливочного мороженого с&nbsp;дробленым
              миндалем и&nbsp;фисташкой под кленовым сиропом
            </div>
          </div>
          <div className={classes.itemButtonWrapper}>
            <button className={cn(classes.itemButton, classes.asteroid)}>
              купить
            </button>
          </div>
        </section>
        <section className={classes.itemContainer}>
          <div className={classes.itemContainerWrapper}>
            <div className={classes.itemImageWrapper}>
              <Image
                className={classes.itemImage}
                src="/images/items/orbit/orbit_x5nsrq_c_scale,w_200.png"
                layout="fill"
                objectFit="contain"
                alt="Around the Orbit"
              />
            </div>
            <div className={classes.itemHeaderWrapper}>
              <header className={cn(classes.itemHeader, classes.orbit)}>
                around the orbit
              </header>
            </div>
            <div className={classes.itemCapacity}>60 / 100 ml</div>
            <div className={classes.itemDescription}>
              Нежный ароматный вкус натурального клубничного компота утолит
              жажду вкусовых рецепторов и&nbsp;освежит воспоминания о&nbsp;ярких
              солнечных днях, проведенных в&nbsp;деревне
            </div>
          </div>
          <div className={classes.itemButtonWrapper}>
            <button className={cn(classes.itemButton, classes.orbit)}>
              купить
            </button>
          </div>
        </section>
        <section className={classes.itemContainer}>
          <div className={classes.itemContainerWrapper}>
            <div className={classes.itemImageWrapper}>
              <Image
                className={classes.itemImage}
                src="/images/items/jam/jam_o32jgj_c_scale,w_200.png"
                layout="fill"
                objectFit="contain"
                alt="Space Jam"
              />
            </div>
            <div className={classes.itemHeaderWrapper}>
              <header className={cn(classes.itemHeader, classes.jam)}>
                space jam
              </header>
            </div>
            <div className={classes.itemCapacity}>60 / 100 ml</div>
            <div className={classes.itemDescription}>
              Космическое сочетание вкусов раскрывается в&nbsp;деталях
              мармеладных оттенков прохладного космического джема&nbsp;&mdash;
              если мармелад, то&nbsp;только космический
            </div>
          </div>
          <div className={classes.itemButtonWrapper}>
            <button className={cn(classes.itemButton, classes.jam)}>
              купить
            </button>
          </div>
        </section>
        <section className={classes.itemContainer}>
          <div className={classes.itemContainerWrapper}>
            <div className={classes.itemImageWrapper}>
              <Image
                className={classes.itemImage}
                src="/images/items/dreams/dreams_e4tfrc_c_scale,w_200.png"
                layout="fill"
                objectFit="contain"
                alt="Moon Dreams"
              />
            </div>
            <div className={classes.itemHeaderWrapper}>
              <header className={cn(classes.itemHeader, classes.dreams)}>
                moon dreams
              </header>
            </div>
            <div className={classes.itemCapacity}>60 / 100 ml</div>
            <div className={classes.itemDescription}>
              Мягкий ненавязчивый вкус домашнего овсяного печенья раскрывается
              в&nbsp;легких оттенках свежевыпеченного печенья и&nbsp;послевкусии
              овсяных хлопьев
            </div>
          </div>
          <div className={classes.itemButtonWrapper}>
            <button className={cn(classes.itemButton, classes.dreams)}>
              купить
            </button>
          </div>
        </section>
        <section className={classes.itemContainer}>
          <div className={classes.itemContainerWrapper}>
            <div className={classes.itemImageWrapper}>
              <Image
                className={classes.itemImage}
                src="/images/items/gravity/gravity_zbngh9_c_scale,w_200.png"
                layout="fill"
                objectFit="contain"
                alt="Zero Gravity"
              />
            </div>
            <div className={classes.itemHeaderWrapper}>
              <header className={cn(classes.itemHeader, classes.gravity)}>
                zero gravity
              </header>
            </div>
            <div className={classes.itemCapacity}>60 / 100 ml</div>
            <div className={classes.itemDescription}>
              Аромат классической жевательной резинки раскрывается
              в&nbsp;многогранном вкусе с&nbsp;множеством оттенков и&nbsp;уносит
              в&nbsp;космос, где нет гравитации
            </div>
          </div>
          <div className={classes.itemButtonWrapper}>
            <button className={cn(classes.itemButton, classes.gravity)}>
              купить
            </button>
          </div>
        </section>
      </section>
      <section className={classes.orderContainer}>
        <div className={classes.orderFormWrapper}>
          <div className={classes.orderFormHeading}>
            Просто оставьте нам свою почту
          </div>
          <form action="/api/order" method="post" className={classes.orderForm}>
            <input
              className={cn(classes.orderFormControl, classes.orderFormInput)}
              type="text"
              name="email"
              placeholder="Адрес электронной почты"
            />
            <input type="hidden" name="_csrf" />
            <button
              className={cn(classes.orderFormControl, classes.orderFormButton)}
            >
              отправить
            </button>
          </form>
          <div className={classes.orderFormHeading}>или позвоните</div>
          <div className={classes.orderFormPhone}>+7 926 385 37-51</div>
        </div>
      </section>
    </div>
  );
}
